PolyLoss
ivan-chai/exact pull request #1
Opened 2024-02-21 10:21 UTC by stdereka

* Add PolyLoss implementation
* Add PolyLoss template config
* Bump up Ubuntu version in Dockerfile
* Fix protobuf version

2024-02-22 11:53 UTC, ivan-chai requested changes

2024-02-22 11:53 UTC, ivan-chai commented on mdn-metric/configs/exact/templates/template-polyloss.yaml
> +      max: 2
max: 5?

2024-02-22 11:53 UTC, ivan-chai commented on mdn-metric/src/mdn_metric/criterion/polyloss.py
> +            poly1 = poly1.sum()
else: assert == "none"

2024-02-22 11:53 UTC, ivan-chai commented on mdn-metric/src/mdn_metric/criterion/polyloss.py
> +        pt = torch.sum(labels_onehot * F.softmax(logits, dim=-1), dim=-1)
softmax.take_along_dim(labels.unsqueeze(-1), dim=-1).squeeze(-1)

2024-02-22 11:53 UTC, ivan-chai commented on mdn-metric/src/mdn_metric/criterion/polyloss.py
> +        pt = torch.sum(labels_onehot * F.softmax(logits, dim=-1), dim=-1)
Не придется с one_hot мутить.

2024-02-23 13:58 UTC, stdereka commented on mdn-metric/configs/exact/templates/template-polyloss.yaml
> +      max: 2
Done

2024-02-23 13:58 UTC, stdereka commented on mdn-metric/src/mdn_metric/criterion/polyloss.py
> +            poly1 = poly1.sum()
Done

2024-02-23 13:59 UTC, stdereka commented on mdn-metric/src/mdn_metric/criterion/polyloss.py
> +        pt = torch.sum(labels_onehot * F.softmax(logits, dim=-1), dim=-1)
А может ну его?) Так более читаемо, по производительности нормально

2024-02-26 07:54 UTC, merged